import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { EMIResult, AmortizationRow } from './calculations';
import { generateAmortizationSchedule, formatCurrency } from './calculations';

export const exportAmortizationPDF = (emiResult: EMIResult): void => {
    const doc = new jsPDF();

    // Add header
    doc.setFontSize(20);
    doc.setTextColor(43, 127, 246);
    doc.text('Smart EMI Calculator', 105, 20, { align: 'center' });

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Amortization Schedule', 105, 30, { align: 'center' });

    // Add loan details
    doc.setFontSize(12);
    doc.text('Loan Details:', 20, 45);

    doc.setFontSize(10);
    doc.text(`Principal Amount: ${formatCurrency(emiResult.principal)}`, 20, 55);
    doc.text(`Interest Rate: ${emiResult.interestRate}% per annum`, 20, 62);
    doc.text(`Loan Tenure: ${emiResult.tenure} months`, 20, 69);

    doc.text(`Monthly EMI: ${formatCurrency(emiResult.monthlyEMI)}`, 120, 55);
    doc.text(`Total Interest: ${formatCurrency(emiResult.totalInterest)}`, 120, 62);
    doc.text(`Total Payment: ${formatCurrency(emiResult.totalPayment)}`, 120, 69);

    // Generate schedule
    const schedule = generateAmortizationSchedule(emiResult);

    // Prepare table data
    const tableData = schedule.map((row) => [
        row.month.toString(),
        formatCurrency(row.payment),
        formatCurrency(row.principalPaid),
        formatCurrency(row.interestPaid),
        formatCurrency(row.balance),
    ]);

    // Add table
    autoTable(doc, {
        startY: 80,
        head: [['Month', 'Payment', 'Principal', 'Interest', 'Balance']],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: [43, 127, 246],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
        styles: {
            fontSize: 9,
            cellPadding: 3,
        },
        columnStyles: {
            0: { halign: 'center', cellWidth: 20 },
            1: { halign: 'right', cellWidth: 35 },
            2: { halign: 'right', cellWidth: 35 },
            3: { halign: 'right', cellWidth: 35 },
            4: { halign: 'right', cellWidth: 35 },
        },
    });

    // Add footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Page ${i} of ${pageCount}`,
            105,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
        doc.text(
            'Generated by Smart EMI Calculator',
            105,
            doc.internal.pageSize.height - 5,
            { align: 'center' }
        );
    }

    // Save the PDF
    const fileName = `amortization_schedule_${new Date().getTime()}.pdf`;
    doc.save(fileName);
};
